### ISSUE TITLE
error when connecting to cogito

### ISSUE THREAD

**Issue by gtsync** [Tukks/cogito#30]
When I try to access cogito at `http://<my local ip>:8585`, I get an error at the top of the page
"An error occurred, detail: Code: 403, Message: Http failure response for http:// my local IP:8585/api/thoughts: 403 OK"
I create a new account, but when attempting to sign in, get the same message..
my docker-compose:

```
services:
  cogito:
    image: tukks/cogito:v1.3-alpha
    ports:
      - "8585:9191"
    volumes:
      - ./db:/app/db
      - ./image:/app/image
    environment:
      - APP_JWT_SECRET="xjurrsalgwfnmgozhvhxhiocehsqqppxjpxvyucrrsaqppxvwiobttgjizaadfuhizkbilzjlsniargqsdrjswfhsutrljlrjmxinaqqkeqhfhiurtlfqzwsqwhdwhvc"
#   - API_TWITTER_KEY_SECRET="YOUR_API_TWITTER_KEY_SECRET"
#     - API_TWITTER_KEY="YOUR_API_TWITTER_KEY"
#     - HTTPS_ONLY=true # true if you use https
```
